prometheus_alertmanager_config:
  - scheme: http
    static_configs:
      - targets: ["host:9093"]

prometheus_targets:
  node:
    - targets:
      - host:9100
  alertmanager:
    - targets:
      - host:9093

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "/etc/prometheus/file_sd/node.yml"
  - job_name: "alertmanager"
    file_sd_configs:
      - files:
          - "/etc/prometheus/file_sd/alertmanager.yml"

prometheus_alert_rules_files:
  - alert_rules/somethings.rules

prometheus_alert_rules: []
