#указываем ссылку на репозиторий с ролью, версию и название роли
- src: https://адрес_репозитория_с_ролью
  version: номер_версии #всегда указывайте конкретную версию, чтобы избежать проблем
  name: название_роли

#роль для Prometheus. Сейчас она со статусом "deprecated", но это все равно самая лучшая роль и я ее сама продолжнаю использовать
- src: https://github.com/cloudalchemy/ansible-prometheus
  version: 4.0.0
  name: ansible-prometheus