#указываем ссылку на репозиторий с ролью, версию и название роли
- src: https://адрес_репозитория_с_ролью
  version: номер_версии #всегда указывайте конкретную версию, чтобы избежать проблем
  name: название_роли